### ISSUE TITLE
500 Internal Server Error when using encoded URLs

### ISSUE THREAD

**Issue by sw3dish** [umdio/umdio#12]
The server returns a 500 status code when certain characters are used in the URL after being encoded using PHP's `urlencode` [function](http://us2.php.net/manual/en/function.urlencode.php) (or any similar functionality).

For example: The call to `http://api.umd.io/v0/courses?credits=2,3&` is valid; however, the equivalent URL encoded call to `http://api.umd.io/v0/courses?credits%3D2%2C3%26` fails.

**Comment by jaxgeller** [comment]
Seems to be the `= (%3D)` that causes the problem. For example

`http://api.umd.io/v0/courses?credits=2%2C3&` --> okay
`http://api.umd.io/v0/courses?credits=2,3%26` --> okay
`http://api.umd.io/v0/courses?credits%3D2,3&` --> fails

It could be a problem with nginx not decoding the values properly, since Rack out of the box [should decode them](http://www.whyfaq.com/questions/28987085/how-to-decode-route-parameters-in-sinatra).

**Comment by rrcobb** [comment]
We definitely should not be returning a 500 error, but I'm pretty sure that %3D is meant to be interpreted as a part of a string in a parameter, not as part of the url parameter syntax. So, /url/prefix?param=url%20encoded%20string%20with%20symbols%20like%3D%2C%2B%2C%20and%20%5C would be matched by the /url/prefix and have decoded parameter 'param' with value 'url encoded string with symbols like =,+, and /'

As far as I can tell, we should be giving a better error, but users should only url-encode parameters, not the url parameter syntax ('?','=','&'). I could be wrong about the standard though, so let me know if you see something contradictory.

**Comment by nickaversano** [comment]
Any parameter without an equals sign breaks searching:
`http://api.umd.io/v0/courses?credits` --> 500 error
`http://api.umd.io/v0/courses?asdf` --> 500 error

**Comment by sw3dish** [comment]
@rrcobb was not aware that was the case. Thanks for clarifyinh!

**Comment by erdum** [comment]
Thanks, @rrcobb problem is that we only have to encode the data and the parameter name.
