### ISSUE TITLE
Certain methods do not support ?page and ?per_page parameters

### ISSUE THREAD

**Issue by sw3dish** [umdio/umdio#19]
The `http://api.umd.io/v0/courses/list` method does not support `?page` or `?per_page` parameters. Per the documentation, it seems like, since this endpoint returns a large number of items (4261 for 2015 spring semester) that it should support pagination.

**Comment by rrcobb** [comment]
We've got the list as a quick way to get all of the courses from a semester without having to deal with paging - an index. 

That should be explicit in the docs, and the endpoint itself might need adjustment too - maybe return an array of all the course_ids instead of thousands of three-item objects.
