### ISSUE TITLE
sections waitlist count is incorrect

### ISSUE THREAD

**Issue by tybug** [umdio/umdio#236]
waitlist on sections endpoint is wrong. Seems we're concatenating the waitlist and holdfile numbers when we scrape instead of just pulling the waitlist number. Not sure why, the scraping code looks correct at a glance.

eg:
https://api.umd.io/v1/courses/math403/sections returns waitlist: 90 but should be 9. https://app.testudo.umd.edu/soc/202208/MATH/MATH403

**Comment by javathunderman** [comment]
This is because the scraper presumes that the waitlist and holdfile are rendered using different HTML classes, when they actually just use the same class (misleadingly just called "waitlist-count").

https://github.com/umdio/umdio/blob/f85374613e7ffe10bc409ad52db71dbf8a4a4689/app/scrapers/sections_scraper.rb#L69


![Screenshot from 2022-04-06 13-52-58](https://user-images.githubusercontent.com/6887325/162038032-c6c87ee1-ec78-4159-a4f2-6d7f33f595c1.png)

**Comment by tybug** [comment]
closed by https://github.com/umdio/umdio/pull/237
