### ISSUE TITLE
Website formatting breaks

### ISSUE THREAD

**Issue by wkunkel** [umdio/umdio#4]
Hi, I don't know if this is an appropriate place to report issues with your website, but if you click on any of the links under "API" except "Introduction" or "Tips and Tricks", it highlights the link above the one you clicked. Also, if you click on any of them except "Introduction", and then scroll back to the top, the menu moves up under the "umd.io" link and the space above the "Introduction" heading disappears.

**Comment by wkunkel** [comment]
I've just noticed that "Tips and Tricks" is also hidden under the footer if you just scroll the page instead of clicking the links.

**Comment by rrcobb** [comment]
This is the perfect place to report issues, thanks for doing so. 

I see the highlighting problem - it's happening because the highlight is autodetecting where you are on the page. When you click a section at the bottom, the top of your window is still in the section above the one you are reading, and that is the link that gets highlighted. We'll work on it.

I haven't been able to replicate the menu hiding or losing the "Tips and Tricks" section - any more you can tell about your setup (browser, etc)?

**Comment by rrcobb** [comment]
Has anyone been able to replicate the issues with the nav disappearing or the footer hiding the last section on the page? I am closing without more information, but feel free to reopen if anyone runs into this again.
