### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by McIntireEvan** [umdio/umdio#54]
When I was setting up HTTPS, there were some issues concerning www.umd.io, specifically the way the DNS is configured. Right now, it's not an issue, as it just seems to redirect at a DNS level, but I wanted to make sure this is intended and fine

Also, I'd like to request a beta.umd.io domain to test things on the production server with, without breaking what we have

@rrcobb

**Comment by rrcobb** [comment]
Mhm! Seems likely that something is wacky, I was mostly making it up when I set up namecheap back in the day - beta.* seems like a useful subdomain. 

I can add the beta.umd.io subdomain pretty easily I think, but I’m not sure exactly what is up with the dns, and have pretty low interest in debugging. I’ll see if there’s an easy way to add managers on the namecheap account so that you can take a look

**Comment by nyaculak** [comment]
@rrcobb We could also move the DNS over to Digital Ocean's name servers.

**Comment by McIntireEvan** [comment]
DNS stuff is all good at the moment, all on namecheap. In the future, we should look into consolidating dns onto DO or something else

**Comment by McIntireEvan** [comment]
This is now done - all DNS is done on DO now
