### ISSUE TITLE
Ignoring sentences directly after "Prerequisites: ..." and other relationships

### ISSUE THREAD

**Issue by IsabellaS09** [umdio/umdio#7]
If you look at a course like ENEE150, it is ignoring the sentence directly after the sentence with "Prerequisite:" in it. But the sentence after is a continuation of the prerequisites.

**Comment by rrcobb** [comment]
This is tricky - we are pulling from Testudo and attempting to pattern-match the unstructured text in order to create structure. If you look at the scraper, it's looking from the word 'Prerequisite' to the next period ('.'). If you want to play with the regular expression and do negative lookahead for words like Corequisite, we might be able to scrape the whole phrase, but there's no easy fix for this until we are working with a database that has a 'prerequisite' field.

**Comment by nickaversano** [comment]
Maybe we can do something without regular expressions. Just take the entire description and try to split the whole string on keywords like "Prerequisite," "Corequisite," and so on.

**Comment by IsabellaS09** [comment]
You could try splitting up the description by sentences, and checking for keywords ("Prerequisite", "Corequisite" , etc.) and check the following sentences for "And" or "Or" being the first word? In general I think that's how they are formatted.

**Comment by rrcobb** [comment]
Cool, those are good thoughts. We'll split on the keyword strings instead of regexing. I'll get to it in the scraper update.

**Comment by rrcobb** [comment]
Still thinking about ways to attack this one. I'm not sure how vital it is, because all of the info should appear anyway in the description field (maybe not ideal behavior, but that's another story). 

@IsabellaS09  if you have ideas for how to do this, go right ahead.

**Comment by sdrozzy** [comment]
This seems to have been fixed somewhere over the past few years. Closing.
